DROP TABLE stock;
CREATE TABLE stock (
  symbol CHAR(10) PRIMARY KEY,
  price  INT NOT NULL
);
INSERT INTO stock VALUES ('SUNW', 68);
INSERT INTO stock VALUES ('CyAs', 22);
INSERT INTO stock VALUES ('DUKE', 6);
INSERT INTO stock VALUES ('ABStk', 18);
INSERT INTO stock VALUES ('JSVco', 9);
INSERT INTO stock VALUES ('TMAs', 82);
INSERT INTO stock VALUES ('BWInc', 11);
INSERT INTO stock VALUES ('GMEnt', 44);
INSERT INTO stock VALUES ('PMLtd', 203);
INSERT INTO stock VALUES ('JDK', 33);
